version: '3.6'

services:
  redis-master:
    container_name: redis-master
    image: redis:alpine3.18
    command: [ "redis-server", "/etc/redis", "--port", "6379", "--requirepass", "Login@345" ]
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./conf:/etc/redis
    networks:
      cercli_net:
        ipv4_address: 172.20.1.10

  redis-slave1:
    container_name: redis-slave1
    image: redis:alpine3.18
    command: ["redis-server", "/etc/redis", "--slaveof", "redis-master", "6379", "--masterauth", "Login@345", "--requirepass", "Login@345" ]
    depends_on:
      - redis-master
    links:
      - redis-master
    expose:
      - 6379
    ports:
      - "6380:6379"
    volumes:
      - ./conf:/etc/redis
    networks:
      cercli_net:
        ipv4_address: 172.20.1.11

  redis-slave2:
    container_name: redis-slave2
    image: redis:alpine3.18
    command: ["redis-server", "/etc/redis", "--slaveof", "redis-master", "6379", "--masterauth", "Login@345", "--requirepass", "Login@345" ]
    depends_on:
      - redis-master
    links:
      - redis-master
    expose:
      - 6379
    ports:
      - "6381:6379"
    volumes:
      - ./conf:/etc/redis
    networks:
      cercli_net:
        ipv4_address: 172.20.1.12

  redis-slave3:
    container_name: redis-slave3
    image: redis:alpine3.18
    command: ["redis-server", "/etc/redis", "--slaveof", "redis-master", "6379", "--masterauth", "Login@345", "--requirepass", "Login@345" ]
    depends_on:
      - redis-master
    links:
      - redis-master
    expose:
      - 6379
    ports:
      - "6382:6379"
    volumes:
      - ./conf:/etc/redis
    networks:
      cercli_net:
        ipv4_address: 172.20.1.13

  redis-sentinel1:
    container_name: redis-sentinel1
    image: redis:alpine3.18
    command: [ "redis-sentinel", "/etc/redis/sentinel1.conf", "--sentinel" ]
    links:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    expose:
      - 26379
    ports:
      - "26379:26379"
    volumes:
      - ./conf:/etc/redis
    depends_on:
      - redis-master
    networks:
      cercli_net:
        ipv4_address: 172.20.1.14


  redis-sentinel2:
    container_name: redis-sentinel2
    image: redis:alpine3.18
    command: [ "redis-sentinel", "/etc/redis/sentinel2.conf", "--sentinel" ]
    links:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    expose:
      - 26379
    ports:
      - "26380:26379"
    volumes:
      - ./conf:/etc/redis
    depends_on:
      - redis-master
    networks:
      cercli_net:
        ipv4_address: 172.20.1.15


  redis-sentinel3:
    container_name: redis-sentinel3
    image: redis:alpine3.18
    command: [ "redis-sentinel", "/etc/redis/sentinel3.conf", "--sentinel" ]
    links:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    expose:
      - 26379
    ports:
      - "26381:26379"
    volumes:
      - ./conf:/etc/redis
    depends_on:
      - redis-master
    networks:
      cercli_net:
        ipv4_address: 172.20.1.16


  redis-sentinel4:
    container_name: redis-sentinel4
    image: redis:alpine3.18
    command: [ "redis-sentinel", "/etc/redis/sentinel4.conf", "--sentinel" ]
    links:
      - redis-master
      - redis-slave1
      - redis-slave2
      - redis-slave3
    expose:
      - 26379
    ports:
      - "26382:26379"
    volumes:
      - ./conf:/etc/redis
    depends_on:
      - redis-master
    networks:
      cercli_net:
        ipv4_address: 172.20.1.17

networks:
  cercli_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
